services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 1111:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
#  keycloak:
#    container_name: keycloak-bsn
#    image: quay.io/keycloak/keycloak:24.0.2
#    ports:
#      - 9090:8080
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    networks:
#      - spring-demo
#    command:
#      - "start-dev"

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
#    container_name: elasticSearch
#    environment:
#      - discovery.type=single-node
#      - ELASTIC_PASSWORD=password
#    ports:
#      - "9200:9200"  # HTTP port
#      - "9300:9300"  # Transport port
#    networks:
#      - spring-demo
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.8.2
#    container_name: kibana
#    environment:
#      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
#      ELASTICSEARCH_USERNAME: elastic
#      ELASTICSEARCH_PASSWORD: password
#    ports:
#      - "5601:5601"  # Kibana port
#    networks:
#      - spring-demo
#    depends_on:
#      - elasticsearch

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
#  esdata:
#    driver: local
#  keycloak:
#    driver: local