spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json # Tell OpenAPI documentation generated will assume
                                                # that all your controllers produce json

server:
  servlet:
    context-path: /api/v1/