spring:
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    url: jdbc:postgresql://localhost:1111/book_social_network
#    user: username
#    password: password

  datasource:
    url: jdbc:postgresql://localhost:1111/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  mail:
#    host: localhost
#    port: 1025
#    username: mohammad
#    password: mohammad
#    properties:
#      mail:
#        smtp:
#          trust: "*" # not recommended for production
#        auth: true
#        starttls:
#          enabled: true
#        connectiontimeout: 5000
#        timeout: 3000
#        writetimeout: 5000

  mail:
    host: smtp.gmail.com
    port: 587
    username: mohammadalabed792@gmail.com
    password: tpkxkuvkbqqcaids
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/book-social-network"
#application:
#  file:
#    uploads:
#      photos-output-path: ./uploads

application:
  security:
    jwt:
      secret-key: 86a1d440fcee3d4404666a19d7c762346bccb09c92987b1024febfd5dc7d0611
      expiration: 8640000

  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

  file:
    uploads:
      photos-output-path: ./uploads # file location

server:
  port: 8088


